spring:
  application:
    name: api
  datasource:
    #    url: jdbc:mysql://soknem.rwlb.eu-west-1.rds.aliyuncs.com:3306/api
    #    username: soknem
    #    password: soknem@123
    url: jdbc:mysql://localhost:3306/plasto
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
media:
  storage-path: file
  base-uri: http://localhost:8080
  image-end-point: /api/v1/files